name: Frontend CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install HTML Hint (optional)
        run: |
          npm install -g htmlhint

      - name: Validate HTML files
        run: |
          htmlhint **/*.html || true
